//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/07/2017 20:21:11
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Kassyi.NFC.Kelmis.Strings
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Can't use nfc reader"
        /// </summary>
        public static string CanNotUseReader
        {
            get
            {
                return resourceLoader.GetString("CanNotUseReader");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Can't use app"
        /// </summary>
        public static string Disabled
        {
            get
            {
                return resourceLoader.GetString("Disabled");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "History is not enough"
        /// </summary>
        public static string HistoryIsNotEnough
        {
            get
            {
                return resourceLoader.GetString("HistoryIsNotEnough");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "----"
        /// </summary>
        public static string Hyphen
        {
            get
            {
                return resourceLoader.GetString("Hyphen");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Reading"
        /// </summary>
        public static string Reading
        {
            get
            {
                return resourceLoader.GetString("Reading");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Read complete. Release the card"
        /// </summary>
        public static string ReleaseCard
        {
            get
            {
                return resourceLoader.GetString("ReleaseCard");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Touch the SF card"
        /// </summary>
        public static string TouchIcCard
        {
            get
            {
                return resourceLoader.GetString("TouchIcCard");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Touch the SF card again"
        /// </summary>
        public static string TouchIcCardAgain
        {
            get
            {
                return resourceLoader.GetString("TouchIcCardAgain");
            }
        }
    }
}
